// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface KomorebiWorkspaceProps { label: string | null, label_offline: string | null, label_tooltip: string | null, hide_empty: boolean | null, cycle_on_scroll: boolean | null, }