// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CatCommandResponse {
  stdout: string | null;
  stderr: string | null;
  status: number | null;
}
