// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatCommandOptions } from "./CatCommandOptions";

export interface CatWidgetProps {
  class: string | null;
  label: string | null;
  target: CatCommandOptions | null;
}
