// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomWidgetProps } from "./custom\\CustomWidgetProps";
import type { DateTimeWidgetProps } from "./datetime\\DateTimeWidgetProps";
import type { TextWidgetProps } from "./text\\TextWidgetProps";

export type ConfiguredWidget =
  | ({ kind: "TextWidget" } & TextWidgetProps)
  | ({ kind: "DateTimeWidget" } & DateTimeWidgetProps)
  | ({ kind: "CustomWidget" } & CustomWidgetProps);
