// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfiguredWidget } from "./ConfiguredWidget";

export interface ConfiguredWidgets { left: Array<ConfiguredWidget>, middle: Array<ConfiguredWidget>, right: Array<ConfiguredWidget>, }