// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BarEdge } from "./BarEdge";
import type { BlurEffect } from "./BlurEffect";
import type { ColumnBarWidgets } from "./ColumnBarWidgets";

export interface BarConfig {
  thickness: number | null;
  edge: BarEdge | null;
  screens: Array<string> | null;
  widgets: ColumnBarWidgets;
  win_app_bar: boolean | null;
  always_on_top: boolean | null;
  blur_effect: BlurEffect | null;
  transparency: boolean | null;
}
