// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BarEdge } from "./BarEdge";
import type { BlurEffect } from "./BlurEffect";
import type { ColumnBarWidgets } from "./ColumnBarWidgets";

export interface BarConfig { thickness: number, edge: BarEdge, win_app_bar: boolean, always_on_top: boolean, transparency: boolean, blur_effect: BlurEffect | null, screens: Array<string> | null, widgets: ColumnBarWidgets, }