// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ColumnBarWidgets {
  left: Array<string> | null;
  middle: Array<string> | null;
  right: Array<string> | null;
}
