// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BarConfig } from "./BarConfig";
import type { ConfiguredWidget } from "..\\widget\\ConfiguredWidget";

export interface YasbConfig { bars: Record<string, BarConfig>, widgets: Record<string, ConfiguredWidget> | null, }