// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallbackTypeExecOptions } from "./CallbackTypeExecOptions";

export type CallbackType =
  | "none"
  | "toggle"
  | "update"
  | {
      exec: CallbackTypeExecOptions;
    };
