// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfiguredWidget } from "..\\ConfiguredWidget";

export type ConfiguredOrDefaultWidget = { Configured: ConfiguredWidget } | {
  Default: { kind: string };
};
