// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfiguredOrDefaultWidget } from "./ConfiguredOrDefaultWidget";

export interface ConfiguredOrDefaultWidgets {
  left: Array<ConfiguredOrDefaultWidget>;
  middle: Array<ConfiguredOrDefaultWidget>;
  right: Array<ConfiguredOrDefaultWidget>;
}
