// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface JsonViewerPopupOptions { width: number | null, height: number | null, padding: number | null, class: string | null, max_depth: number | null, expanded: boolean | null, update_on_interval: boolean | null, }