// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PopupOptions { width: number, height: number, padding: number, class: string | null, }