// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallbackType } from "./CallbackType";

export interface WidgetCallbacks {
  on_left: CallbackType | null;
  on_middle: CallbackType | null;
  on_right: CallbackType | null;
  on_hover: CallbackType | null;
}
