// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IgnoreLists } from "./IgnoreLists";
import type { WidgetCallbacks } from "..\\base\\WidgetCallbacks";

export interface ActiveWindowWidgetProps {
  class: string | null;
  label: string | null;
  label_alt: string | null;
  label_tooltip: string | null;
  exclusive: boolean | null;
  ignore: IgnoreLists | null;
  callbacks: WidgetCallbacks | null;
}
