// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActiveWindowCallbackType } from "./ActiveWindowCallbackType";
import type { IgnoreLists } from "./IgnoreLists";
import type { WidgetCallbacks } from "..\\base\\WidgetCallbacks";

export interface ActiveWindowWidgetProps { class: string | null, label: string | null, label_alt: string | null, label_max_len: number | null, is_monitor_exclusive: boolean | null, ignored_windows: IgnoreLists | null, callbacks: WidgetCallbacks<ActiveWindowCallbackType> | null, }