// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecOptions } from "..\\base\\ExecOptions";

export type ActiveWindowCallbackType = "toggle_label" | "json_viewer" | { exec: ExecOptions };