// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ActiveWindowPayload { hwnd: number, handle: number | null, pid: number, tid: number, title: string | null, class: string | null, exe_path: string | null, exe_name: string | null, monitor: string | null, }