// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BasePopupProps } from "..\\base\\BasePopupProps";

export interface CalendarProps { popup: BasePopupProps | null, locale: string | null, }