// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DateTimeWidgetProps {
  class: string | null;
  format: string | null;
  interval: number | null;
}
