// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarPopupOptions } from "..\\base\\CalendarPopupOptions";
import type { DateTimeCallbackType } from "..\\base\\DateTimeCallbackType";
import type { WidgetCallbacks } from "..\\base\\WidgetCallbacks";

export interface DateTimeWidgetProps { class: string | null, formats: Array<string> | null, timezones: Array<string> | null, interval: number | null, calendar: CalendarPopupOptions | null, callbacks: WidgetCallbacks<DateTimeCallbackType> | null, }