// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarProps } from "./CalendarProps";
import type { DateTimeCallbackType } from "./DateTimeCallbackType";
import type { WidgetCallbacks } from "..\\base\\WidgetCallbacks";

export interface DateTimeWidgetProps { class: string | null, formats: Array<string> | null, timezones: Array<string> | null, interval: number | null, calendar: CalendarProps | null, callbacks: WidgetCallbacks<DateTimeCallbackType> | null, }