// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallbackTypeExecOptions } from "..\\base\\CallbackTypeExecOptions";

export type CustomCallbackType = "toggle_label" | "toggle_json_viewer" | { exec: CallbackTypeExecOptions };