// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomCallbackType } from "./CustomCallbackType";
import type { CustomCommandOptions } from "./CustomCommandOptions";
import type { WidgetCallbacks } from "..\\base\\WidgetCallbacks";

export interface CustomWidgetProps { class: string | null, label: string | null, label_alt: string | null, label_tooltip: string | null, command: CustomCommandOptions | null, callbacks: WidgetCallbacks<CustomCallbackType> | null, }