// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SystemCpuInfo } from "./SystemCpuInfo";
import type { SystemLoadAverage } from "./SystemLoadAverage";

export interface OperatingSystemInfo {
  name: string | null;
  ver: string | null;
  host: string | null;
  boot_time: bigint;
  uptime: bigint;
  num_cpus: number;
  num_cores: number | null;
  cpu_info: SystemCpuInfo;
  load_avg: SystemLoadAverage;
}
