// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WidgetCallbacks } from "..\\base\\WidgetCallbacks";

export interface SysInfoWidgetProps {
  class: string | null;
  label: string | null;
  label_alt: string | null;
  label_tooltip: string | null;
  interval: number | null;
  callbacks: WidgetCallbacks | null;
}
