// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SystemCpuInfo { name: string, brand: string, vendor_id: string, frequency: bigint, cpu_usage: number, }