// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperatingSystemInfo } from "./OperatingSystemInfo";
import type { SystemComponentsInfo } from "./SystemComponentsInfo";
import type { SystemCpuInfo } from "./SystemCpuInfo";
import type { SystemMemoryInfo } from "./SystemMemoryInfo";
import type { SystemNetowrkData } from "./SystemNetowrkData";

export interface SystemInformation {
  sys: OperatingSystemInfo;
  mem: SystemMemoryInfo;
  cpus: Array<SystemCpuInfo>;
  networks: Record<string, SystemNetowrkData>;
  components: Array<SystemComponentsInfo>;
}
