// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SystemDiskInfo {
  kind: string;
  name: string;
  file_system: string;
  mount_point: string;
  total_space: bigint;
  available_space: bigint;
  is_removable: boolean;
}
