// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SystemNetowrkData {
  received: bigint;
  transmitted: bigint;
  total_received: bigint;
  total_transmitted: bigint;
}
