// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SystemMemoryInfo { mem_used: bigint, mem_total: bigint, swap_used: bigint, swap_total: bigint, }